@startuml

class CorrelativeLoad {
  + {static} data(): void
  - {static} dataCareer1(): void
  - {static} dataCareer2(): void
  - {static} dataCareer3(): void
  - {static} dataCareer4(): void
  - {static} dataCareer5(): void
}

@enduml