@startuml

package academichistory {
    !include ./AcademicHistory.puml
    !include ./AcademicHistoryController.puml
    !include ./AcademicHistoryViews.puml
    !include ./AcademicHistorySearch.puml
}

@enduml