@startuml AcademicManager

note "The builders, setters, and getters \n are not included in the diagram." as N1

package main {
    class AcademicManager {
        - loadData(): void
        + main(String[] args): void
    }

    !include ./career/package.career.puml
    !include ./common/package.common.puml
    !include ./site/package.site.puml
    !include ./student/package.student.puml
    !include ./studyplan/package.studyplan.puml
    !include ./subject/package.subject.puml
}

@enduml