@startuml

class CareerController {
    - instance: CareerController
    ---
    + getInstance(): CareerController
    + index(): void
    + create(save: boolean, model: Career): void
    + update(save: boolean, id: int): void
    + view(id: int): void
    + delete(validation: boolean, id: int): void
    + search(viewSubjects: boolean): void
    + viewSubjects(idCareer: int): void
}

@enduml