@startuml

class CareerViews {
    - performSaveOrUpdate(model: Career, nameField: JTextField): void
    - form(model: Career, update: boolean): JPanel
    + index(): List<JComponent>
    + create(model: Career): List<JComponent>
    + update(model: Career): List<JComponent>
    + view(model: Career): List<JComponent>
    + delete(isDelete: boolean, id: int): List<JComponent>
    + search(viewSubjects: boolean): List<JComponent>
    + viewSubjects(model: StudyPlan): List<JComponent>
}

@enduml
