@startuml

class CareerViews {
  + {static} index(): List<JComponent>
  + {static} create(Career model): List<JComponent>
  + {static} update(Career model): List<JComponent>
  + {static} view(Career model): List<JComponent>
  + {static} delete(boolean isDelete, int id): List<JComponent>
  + {static} search(boolean viewSubjects): List<JComponent>
  + {static} viewSubjects(StudyPlan model): List<JComponent>
  - {static} performSaveOrUpdate(Career model, JTextField nameField): void
  - {static} form(Career model, boolean update): JPanel
}

@enduml
