@startuml

class Career {
  + {static} TRANSLATE_NAME : String
  - id : int
  - name : String
  # {static} serial : int
  # {static} all : Map<Integer, Model>

  + {static} getAll() : Map<Integer, Model>
  # {static} addSerial() : void
  + validate() : boolean
  + save() : boolean
  + update() : boolean
  + delete() : void
  + getAttributeValues() : Object[]
  + getAttributeNames() : String[]
  + toString() : String
}


@enduml