@startuml

package career {
    !include ./Career.puml
    !include ./CareerSearch.puml
    !include ./CareerController.puml
    !include ./CareerViews.puml

    Career -- CareerController : Asociación
    CareerController ..> CareerSearch: Dependencia
    CareerController ..> CareerViews: Dependencia
    CareerViews -- Career : Asociación
    CareerViews -- CareerSearch : Asociación
    Career --|> CareerSearch: Herencia
}

@enduml