@startuml

package subject {
    !include ./Subject.puml
    !include ./SubjectSearch.puml
    !include ./SubjectController.puml
    !include ./SubjectViews.puml

    SubjectSearch --|> Subject: Herencia
}

@enduml