@startuml

class Button {
    - static configureButton(text: String, backgroundColor: Color, redirection: Runnable): JButton
    + static success(text: String, redirection: Runnable): JButton
    + static primary(text: String, redirection: Runnable): JButton
    + static secondary(text: String, redirection: Runnable): JButton
    + static info(text: String, redirection: Runnable): JButton
    + static warning(text: String, redirection: Runnable): JButton
    + static danger(text: String, redirection: Runnable): JButton
}

@enduml