@startuml

class Button {
    - static configureButton(String text, Color backgroundColor, Runnable redirection): JButton
    + static success(String text, Runnable redirection): JButton
    + static primary(String text, Runnable redirection): JButton
    + static secondary(String text, Runnable redirection): JButton
    + static info(String text, Runnable redirection): JButton
    + static warning(String text, Runnable redirection): JButton
    + static danger(String text, Runnable redirection): JButton
}

@enduml