@startuml

class Input {
    - static final WIDTH: int
    - static final HEIGHT: int
    - static configureComboBox(comboBox: JComboBox<String> ): void
    - static configureComboBoxWithMap(comboBox: JComboBox<String>, options: Map<?, String>): void
    + static createInput(initialValue: String): JTextField
    + static createDateInput(initialValue: LocalDate): JTextField
    + static createSelect2InputStrInt(options: Map<Integer, String>): JPanel
    + static createSelect2InputStrStr(options: Map<String, String>): JPanel
    + static createSelect2InputBoolStr(): JPanel
}


@enduml