@startuml

class LayOut {
    - static contentPanel: JPanel
    + static mainFrame(): JFrame
    + static sidePanel(redirections: Map<String, Runnable> ): JPanel
    + static sideButton(text: String, redirection: Runnable): JButton
    + static topPanel(): JPanel
    + static contentPanel(): JPanel
    + static getContentPanel(): JPanel
}


@enduml