@startuml

package components {
    !include ./Button.puml
    !include ./Common.puml
    !include ./Input.puml
    !include ./LayOut.puml
    !include ./Text.puml
    !include ./UIComponent.puml

    Common <|-- LayOut : Inheritance
    Common <|-- Text : Inheritance
    Common <|-- UIComponent : Inheritance
    UIComponent <|-- Button : Inheritance
    UIComponent <|-- Input : Inheritance
}

@enduml