@startuml

package components {
    !include ./Button.puml
    !include ./Common.puml
    !include ./Input.puml
    !include ./LayOut.puml
    !include ./Text.puml
    !include ./UIComponent.puml

    Common --|> LayOut : Herencia
    Common --|> Text : Herencia
    Common --|> UIComponent : Herencia
    UIComponent --|> Button : Herencia
    UIComponent --|> Input : Herencia
}

@enduml