@startuml

class Text {
    - static configureLabel(text: String, fontSize: int): JLabel
    + static h1(text: String): JLabel
    + static h2(text: String): JLabel
    + static h3(text: String): JLabel
    + static h4(text: String): JLabel
    + static h5(text: String): JLabel
    + static h6(text: String): JLabel
    + static p(text: String): JLabel
    + static label(text: String): JLabel
}

@enduml