@startuml

class UIComponent {
    + static bigBox(): JPanel
    + static tableModel(data: Map<Integer, Model>): JScrollPane
    + static table(columns: String[], rows: List<Object[]>): JScrollPane
    - static configureTable(model: DefaultTableModel ): JTable
}

@enduml